
#include <stdio.h>
#include <tos.h>

#define TRUE -1
#define FALSE 0

int fh_r;           /* Lese File_handle */
int fh_w;           /* Schreib Filehandle */
char get_zeichen(void),lies_zeichen(void);
char skip_space(void);

char nachher;     /* nÑchstes Zeichen */
long anzahl;        /* Anzahl der Zeilen, die gelesen wurden */
char zeile[1024];   /* nimmt eine Zeile auf */
char *ex="extern";
int counter;        /* ZeilenzÑhler */
char rbuffer[100000];            /* 100 K Buffer */
char wbuffer[100000];            /* Schreibspeicher */
long max_read;
long rpos,wpos;

void main()
{
  /* entwickelt aus einem Variablendefinitions-programm ein
     Programm mit externen Definitionen */
  char z1;

  printf("%cE                               EXTERN.C - Generator V2.2\n",27);
  printf("                                 Ω 1990 by Till Bubeck\n");
	printf("                                Release Date: %s\n\n",__DATE__);
	
  printf("generating....please wait.\n\n");

  counter=0;
  nachher=0;
  anzahl=1;                 /* Es ist noch was da, also lesen */
  strcpy(zeile,"extern ");  /* mit extern beginnen */
  
  if ((fh_r=Fopen("GLOBAL.C",0))<0)
    abbruch("Can't find GLOBAL.C");
  max_read=Fread(fh_r,100000L,rbuffer);
  Fclose(fh_r);
  rpos=0; wpos=0;

	write_line("");
	write_line("/* Externe Variablendeklarationen:");
	write_line("   generated by EXTERN.C - Generator V2.2");
	write_line("   Ω 1991 by Till Bubeck, Ziegeleistr. 28, 7056 Weinstadt */");
	write_line("");
	
  if ((fh_w=Fcreate("EXTERN.C",0))<0) {
    Fclose(fh_r);
    abbruch("Can't create EXTERN.C");
    }

	z1=skip_space();
  nachher=z1;                   /* nachher nochmal zurÅckgeben */

  do {
    get_zeile();
    } while(anzahl!=0);

	write_extern();
}

write_line(str)
char str[];
{
	strcpy(&wbuffer[wpos],str);
	wpos+=strlen(str);
	wbuffer[wpos++]=13;
	wbuffer[wpos++]=10;
}

write_extern()
{
  int fh_w;
  
  if ((fh_w=Fcreate("EXTERN.C",0))<0) {
    abbruch("Can't create EXTERN.C");
    }
  Fwrite(fh_w,wpos,wbuffer);
  Fclose(fh_w);
}

char skip_space()
{
	char z1;
	
  do {                  /* FÅhrende Spaces etc. Åberspringen */
    z1=get_zeichen();
    } while(z1==9 || z1==' ' || z1==13 || z1==10 || z1==';');
	return(z1);
}

get_zeile()
{
  int index,start;
  char z1,str[100];
  register int j,i;

  index=7;
  do {
    zeile[index++]=get_zeichen();
    } while(zeile[index-1]!=';');       /* Bis zum ';' lesen */
  zeile[index++]=13;
  zeile[index++]=10;

  start=0;															/* Sonst eigenes extern nehmen */
  for(i=7;i<20;i++) {										/* Kommt hier EXTERN vor? */
    for(j=0;j<6;j++) if (zeile[i+j]!=ex[j]) break;
    if (j==6) {
      start=i;							/* ja, Startposition merken */
      break;
      }
    }

  for(i=0;i<index-start;i++) {
    wbuffer[wpos++]=zeile[start+i];
    /* Cconout(wbuffer[wpos-1]);		*/
    }

  /* Fwrite(fh_w,(long)(index-start),&zeile[start]); */    /* Zeile schreiben */
  counter++;                    /* Eine Zeile mehr */
  if (counter%10==0) {
    sprintf(str,"%cgetting line: %3d",13,counter);
    Cconws(str);
    }

	z1=skip_space();
  nachher=z1;                   /* nachher nochmal zurÅckgeben */
}

char lies_zeichen()
{
  /* liest alle zeichen, aber Åberspringt '='! */
  char zeichen;

  if (anzahl==0) {
  	write_extern();      /* nichts mehr da, schreiben */
		exit(0);
		}
		
  if (nachher!=0) {                 /* NÑchstes Zeichen schon gelesen? */
    zeichen=nachher;                /* ja, nicht lesen, zurÅckgeben */
    nachher=0;
    }
  else {
    if (rpos>=max_read) anzahl=0;					/* Dateiende erreicht? */
    else {
      anzahl=1;
      zeichen=rbuffer[rpos++];
/*    Cconout(zeichen); */
      }
    }
  return(zeichen);
}

char get_zeichen()
{
  /* Liest, und Åberspringt Kommentare und { } (geschachtelt) und = */
  char z1;
	int tiefe;
	
  z1=lies_zeichen();
  if (z1=='/') {
    nachher=lies_zeichen();          /* nÑchstes Zeichen holen und sichern */
    if (nachher!='*') return(z1);   /* kein Kommentar, erstes Zeichen */
    do {
      do {
        z1=lies_zeichen();
        } while(z1!='*');           /* '*' suchen */
      z1=lies_zeichen();             /* und Zeichen danach holen */
      } while (z1!='/');            /* Solange nicht '/' */
    return(get_zeichen());          /* und nochmal starten */
    }
  if (z1=='{') {
  	tiefe=1;
    do {
      z1=lies_zeichen();
      if (z1=='{') tiefe++;
      if (z1=='}') tiefe--;
      } while(tiefe!=0);
    return(get_zeichen());          /* Klammern Åbersprungen, weitermachen */
    }
	if (z1=='=') {
		do {											/* Ab '=' bis zum ';' Åbersrpingen */
			z1=lies_zeichen();
			} while(z1!=';');
		}
  return(z1);                       /* Kein Kommentar und kein '{' */
}

print(str)
char *str;
{

  Cconws(str);
  Cconout(13);
  Cconout(10);
  Crawcin();
}


abbruch(str)
char *str;
{
  Cconws(str);
  Crawcin();
  gemdos(0);
}

