#################################################################
#
#         Makefile
#
#         Makefile for "Return of Medusa" (UNIX version).
#
# Author: Till Bubeck
#         Eberhard-Karls Universit"at T"ubingen
#         Wilhelm-Schickard-Institut f"ur Informatik
#         Sand 13, 72076 T"ubingen, Fed. Rep. of Germany
#         EMail: bubeck@peanuts.informatik.uni-tuebingen.de
#
#################################################################
#
# iconv -f iso-8859-1 -t UTF-8 atari.c -o dung2.c2 ; sed -i 's/¤/ß/g' dung2.c2 ; sed -i 's/\r$//' dung2.c2
#

include .Makefile-common

#CFLAGS         += -fsanitize=address


